### ISSUE TITLE
Annoying Warning

### ISSUE THREAD

**Issue by The-Robin-Hood** [aadhithya/rajiniPP#30]
# Bug Report
### Checklist
- [x] I am running the latest version of rajinipp.
- [x] I have searched the issues(open / closed) for this issue.
- [x] I have checked the project wiki.
- [x] This problem is reproducible.
- [x] This is not a feature request.

### Current Behaviour
| WARNING  | rajinipp.runner:__init__:35 - LineParser supports only a subset of rajini++ features.
I'm not sure why this warning pops up even for a fresh install.

### Expected Behaviour
Warning could be avoided 

### Steps to Reproduce
Just normal installation and running it

### Stack Trace / Screenshot
![image](https://github.com/aadhithya/rajiniPP/assets/32297581/efe7d2b1-d8e5-4103-afd1-702837d2231f)

### General Info
* **rajinipp version**:   v0.3.1
* **python version**: v3.9.2
* **os platform**: Linux

**Comment by aadhithya** [comment]
this serves exactly the purpose it is meant to: to provide you with a warning. You can easily remove it by commenting this [line](https://github.com/aadhithya/rajiniPP/blob/7a745bf39e6cfec81213d8f20bb8033ca15b1952/rajinipp/runner.py#L34C7-L36C14) in your fork, if you don't want to see it.

**Comment by The-Robin-Hood** [comment]
Suggestion: This Warning may appear if the unsupported keywords are used or only for the first time of running the compiler.
